### ISSUE TITLE
Куда пропал github.com/sberdevices/salutejs ?

### ISSUE THREAD

**Issue by vitalets** [salute-developers/salutejs#10]
Я заводил несколько issues в sberdevices/salutejs. Теперь все переехало в https://github.com/salute-developers/salutejs, но issues пустые. Может быть вы перенесете issues из старого репо? Там много полезного заведено было.

**Comment by sasha-tlt** [comment]
@vitalets, нам жаль, но старые ишью не восстановить. Заведите еще раз, пожалуйста, а мы попробуем их решить
