### ISSUE TITLE
payload.device опциональный?

### ISSUE THREAD

**Issue by vitalets** [salute-developers/salutejs#11]
В какой-то момент поле `payload.device` стало [опциональным](https://github.com/salute-developers/salutejs/blob/9f264aa7821ef86dc4ae709abcbcf320815ddd9f/packages/scenario/src/lib/types/systemMessage.ts#L549). После одновления у меня стал ругаться typescript на несколько мест в коде.
Вопросы:
1. В каких запросах со стороны Сбера поле `payload.device` отсутствует?
2. Может быть сделаем его неопциональным в тех типах сообщений, где оно всегда есть (например MESSAGE_TO_SKILL)? Тогда разработчикам будет сильно проще, т.к. не придется постоянно проверять наличие поля.

**Comment by ivan-ushatsky** [comment]
Исполнено:
https://github.com/salute-developers/salutejs/pull/12
